# -*- coding: utf-8 -*-
"""
/***************************************************************************
 tile2patch
                                 A QGIS plugin
 create patches from tiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-11
        copyright            : (C) 2023 by Ricardo Dalangol
        email                : ricds@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load tile2patch class from file tile2patch.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tile2patch import tile2patch
    return tile2patch(iface)
